
CREATE DATABASE IF NOT EXISTS securecore_auth_mvc
USE securecore_auth_mvc;


CREATE TABLE IF NOT EXISTS roles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS candidates (
    id INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS companies (
    id INT UNSIGNED PRIMARY KEY,
    company_name VARCHAR(150),
    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);

